import React, { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';

// "What do you know about me?" — read straight from the local memory graph.
// Nothing here is generated by a model and nothing leaves the device.
export default function MemoryReportModal({ isOpen, onClose, userId }) {
  const [report, setReport] = useState(null);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!isOpen) return;
    setReport(null); setError('');
    invoke('get_memory_report', { userId })
      .then(setReport)
      .catch((e) => setError(String(e)));
  }, [isOpen, userId]);

  if (!isOpen) return null;

  const t = report?.totals || {};
  const list = (arr, f) => (arr && arr.length ? arr.map(f).join(', ') : 'none yet');
  const asText = () => {
    if (!report) return '';
    const lines = [];
    lines.push(`What Zynkbot knows about you (${(t.first_at || '').slice(0, 10)} to ${(t.last_at || '').slice(0, 10)})`);
    lines.push(`${t.memories} memories, ${t.links} links between them, ${t.entities} named things, ${t.sessions} conversations, ${t.messages} messages`);
    lines.push(`${t.dated} memories carry a real event date; ${t.tagged} have tags`);
    lines.push('');
    lines.push('Categories: ' + list(report.namespaces, (x) => `${x.name} ${x.count}`));
    lines.push('Tags: ' + list(report.tags, (x) => `${x.tag} ${x.count}`));
    lines.push('People: ' + list(report.entities?.person, (x) => `${x.name} (${x.count})`));
    lines.push('Places: ' + list(report.entities?.place, (x) => `${x.name} (${x.count})`));
    lines.push('Organisations: ' + list(report.entities?.org, (x) => `${x.name} (${x.count})`));
    lines.push('Things: ' + list(report.entities?.thing, (x) => `${x.name} (${x.count})`));
    lines.push('');
    lines.push('Timeline (by when it happened):');
    (report.timeline || []).forEach((x) => lines.push(`  ${x.day}  ${x.title}`));
    lines.push('');
    lines.push('Belief changes:');
    (report.belief_changes || []).forEach((x) => lines.push(`  ${x.day}  ${x.kind}: "${x.new_title}" vs "${x.old_title}"${x.notes ? ' — ' + x.notes : ''}`));
    lines.push('');
    lines.push('Tone: ' + list(report.tone, (x) => `${x.label} ${x.count}`));
    lines.push('Extraction outcomes by conversation: ' + list(report.extraction, (x) => `${x.outcome} ${x.count}`));
    if (report.kitchen?.length) {
      lines.push('');
      lines.push('Kitchen:');
      report.kitchen.forEach((x) => lines.push(`  ${x.day}  ${x.title}`));
    }
    return lines.join('\n');
  };
  const copy = async () => {
    try { await navigator.clipboard.writeText(asText()); setCopied(true); setTimeout(() => setCopied(false), 2000); } catch (_) {}
  };

  const h = { color: '#8be9fd', fontSize: '0.95rem', margin: '14px 0 6px 0' };
  const p = { margin: '0 0 4px 0', fontSize: '0.88rem', lineHeight: 1.5, color: '#ececec' };
  const muted = { ...p, color: '#9aa5c4' };
  const btn = { padding: '7px 12px', borderRadius: '6px', border: '1px solid #6272a4', background: 'rgba(98,114,164,0.25)', color: '#8be9fd', cursor: 'pointer', fontWeight: 600, fontSize: '0.85rem' };
  const chip = (text, key) => (
    <span key={key} style={{ display: 'inline-block', margin: '2px 4px 2px 0', padding: '2px 8px', borderRadius: '10px', background: '#2b2d3a', border: '1px solid #44475a', fontSize: '0.8rem', color: '#f8f8f2' }}>{text}</span>
  );

  return (
    <div onClick={onClose} style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', zIndex: 10000, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '10px' }}>
      <div onClick={(e) => e.stopPropagation()} style={{ background: '#22232a', color: '#f8f8f2', borderRadius: '10px', padding: '18px', width: 'min(760px, 96vw)', maxHeight: '92vh', overflowY: 'auto', border: '1px solid #44475a', position: 'relative' }}>
        <button className="modal-close" onClick={onClose} aria-label="Close">×</button>
        <h2 style={{ margin: '0 0 4px 0', color: '#50fa7b', fontSize: '1.15rem' }}>What Zynkbot knows about you</h2>
        <p style={muted}>Read from the memory database on this device. Nothing is sent anywhere.</p>

        {error && <p style={{ color: '#ff5555' }}>{error}</p>}
        {!report && !error && <p style={muted}>Reading…</p>}

        {report && (
          <>
            <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', margin: '8px 0' }}>
              <button style={btn} onClick={copy}>{copied ? '✓ Copied' : '📋 Copy as text'}</button>
            </div>

            <h3 style={h}>In numbers</h3>
            <p style={p}>{t.memories} memories, {t.links} links between them, {t.entities} named things, across {t.sessions} conversations and {t.messages} messages.</p>
            <p style={muted}>From {(t.first_at || '').slice(0, 10)} to {(t.last_at || '').slice(0, 10)}. {t.dated} memories carry the date something happened; {t.tagged} have tags. Both grow as new memories are stored.</p>

            <h3 style={h}>Categories</h3>
            <div>{(report.namespaces || []).map((x, i) => chip(`${x.name} · ${x.count}`, i))}</div>

            <h3 style={h}>Tags</h3>
            <div>{report.tags?.length ? report.tags.map((x, i) => chip(`${x.tag} · ${x.count}`, i)) : <span style={muted}>none yet, tags start with memories stored from now on</span>}</div>

            <h3 style={h}>People, places and things</h3>
            {['person', 'place', 'org', 'thing'].map((k) => (
              <p key={k} style={p}><strong style={{ color: '#9aa5c4' }}>{{ person: 'People', place: 'Places', org: 'Organisations', thing: 'Things' }[k]}:</strong>{' '}
                {report.entities?.[k]?.length ? report.entities[k].map((x) => `${x.name} (${x.count})`).join(', ') : 'none yet'}</p>
            ))}

            <h3 style={h}>Timeline, by when it happened</h3>
            {report.timeline?.length ? report.timeline.map((x) => (
              <p key={x.id} style={p}><span style={{ color: '#9aa5c4', fontVariantNumeric: 'tabular-nums' }}>{x.day}</span>{'  '}{x.title}</p>
            )) : <p style={muted}>No memory has an event date yet. Say when something happened ("yesterday", "last March") and it will appear here.</p>}

            <h3 style={h}>Belief changes</h3>
            {report.belief_changes?.length ? report.belief_changes.map((x, i) => (
              <p key={i} style={p}><span style={{ color: '#9aa5c4' }}>{x.day}</span>{'  '}<em>{x.kind}</em>: "{x.new_title}" vs "{x.old_title}"{x.notes ? <span style={{ color: '#9aa5c4' }}> — {x.notes}</span> : null}</p>
            )) : <p style={muted}>No contradictions recorded yet.</p>}

            <h3 style={h}>Tone</h3>
            <div>{(report.tone || []).map((x, i) => chip(`${x.label} · ${x.count}`, i))}</div>

            {report.kitchen?.length > 0 && (
              <>
                <h3 style={h}>Kitchen</h3>
                {report.kitchen.map((x) => <p key={x.id} style={p}><span style={{ color: '#9aa5c4' }}>{x.day}</span>{'  '}{x.title}</p>)}
              </>
            )}

            <h3 style={h}>Where extraction stopped</h3>
            <p style={muted}>Per conversation, what happened to the last exchange: {(report.extraction || []).map((x) => `${x.outcome} ${x.count}`).join(', ')}.</p>

            <h3 style={h}>Most recent memories</h3>
            {(report.recent || []).map((x) => <p key={x.id} style={p}><span style={{ color: '#9aa5c4' }}>{x.day}</span>{'  '}{x.title} <span style={{ color: '#6272a4' }}>· {x.namespace}</span></p>)}
          </>
        )}
      </div>
    </div>
  );
}
