import React, { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';

// "What do you know about me?" — read straight from the local memory graph.
// Nothing here is generated by a model and nothing leaves the device.
export default function MemoryReportModal({ isOpen, onClose, userId, onOpenMemory, onFilterTag, openSection }) {
  const [report, setReport] = useState(null);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [openSections, setOpenSections] = useState({});
  const [requestedShown, setRequestedShown] = useState(20); // "You asked me to remember": 20 at a time so the top of the report stays short

  useEffect(() => {
    if (!isOpen) return;
    // Reopened from the tag banner: land on the Tags section so the next tag is one tap away.
    if (openSection) setOpenSections((o) => ({ ...o, [openSection]: true }));
    setReport(null); setError('');
    invoke('get_memory_report', { userId })
      .then(setReport)
      .catch((e) => setError(String(e)));
  }, [isOpen, userId, openSection]);

  if (!isOpen) return null;

  const t = report?.totals || {};
  const list = (arr, f) => (arr && arr.length ? arr.map(f).join(', ') : 'none yet');
  const asText = () => {
    if (!report) return '';
    const lines = [];
    lines.push(`What Zynkbot knows about you (${(t.first_at || '').slice(0, 10)} to ${(t.last_at || '').slice(0, 10)})`);
    lines.push(`${t.memories} memories, ${t.links} links between them, ${t.entities} named things, ${t.sessions} conversations, ${t.messages} messages`);
    lines.push(`${t.dated} memories carry a real event date; ${t.tagged} have tags`);
    lines.push('');
    lines.push('Categories: ' + list(report.namespaces, (x) => `${x.name} ${x.count}`));
    lines.push('Tags: ' + list(report.tags, (x) => `${x.tag} ${x.count}`));
    lines.push('People: ' + list(report.entities?.person, (x) => `${x.name} (${x.count})`));
    lines.push('Places: ' + list(report.entities?.place, (x) => `${x.name} (${x.count})`));
    lines.push('Organisations: ' + list(report.entities?.org, (x) => `${x.name} (${x.count})`));
    lines.push('Things: ' + list(report.entities?.thing, (x) => `${x.name} (${x.count})`));
    lines.push('');
    lines.push('Timeline (by when it happened):');
    (report.timeline || []).forEach((x) => lines.push(`  ${x.day}  ${x.title}`));
    lines.push('');
    lines.push('Belief changes:');
    (report.belief_changes || []).forEach((x) => lines.push(`  ${x.day}  ${x.kind}: "${x.new_title}" vs "${x.old_title}"${x.notes ? ' — ' + x.notes : ''}`));
    lines.push('');
    lines.push('Tone: ' + list(report.tone, (x) => `${x.label} ${x.count}`));
    if (report.requested?.length) {
      lines.push('');
      lines.push('You asked me to remember:');
      report.requested.forEach((x) => lines.push(`  ${x.day}  ${x.title}`));
    }
    if (report.kitchen?.length) {
      lines.push('');
      lines.push('Kitchen:');
      report.kitchen.forEach((x) => lines.push(`  ${x.day}  ${x.title}`));
    }
    return lines.join('\n');
  };
  const copy = async () => {
    try { await navigator.clipboard.writeText(asText()); setCopied(true); setTimeout(() => setCopied(false), 2000); } catch (_) {}
  };

  const p = { margin: '0 0 4px 0', fontSize: '0.88rem', lineHeight: 1.5, color: '#ececec' };
  const muted = { ...p, color: '#9aa5c4' };
  const btn = { padding: '7px 12px', borderRadius: '6px', border: '1px solid #6272a4', background: 'rgba(98,114,164,0.25)', color: '#8be9fd', cursor: 'pointer', fontWeight: 600, fontSize: '0.85rem' };
  const chip = (text, key, onClick) => (
    <span key={key} onClick={onClick} title={onClick ? 'Show these memories in the list' : undefined}
      style={{ display: 'inline-block', margin: '2px 4px 2px 0', padding: '2px 8px', borderRadius: '10px', background: '#2b2d3a', border: '1px solid #44475a', fontSize: '0.8rem', color: onClick ? '#8be9fd' : '#f8f8f2', cursor: onClick ? 'pointer' : 'default' }}>{text}</span>
  );
  // Every line that names a memory opens it in the Memory Manager for editing or
  // deleting: the report is a view of the graph, and the graph is the user's to change.
  const link = (id, text) => (
    <button onClick={() => onOpenMemory && onOpenMemory(id)} title="Open this memory to edit or delete it"
      style={{ background: 'none', border: 'none', padding: 0, color: '#8be9fd', cursor: 'pointer', font: 'inherit', textAlign: 'left' }}>
      {text}
    </button>
  );
  // Sections fold: a few weeks of data already made one long scroll a wall of text
  // (2026-09-08). Each header shows its count so a closed section still says something.
  const Section = ({ id, title, count, children, open }) => {
    const isOpen = openSections[id] ?? !!open;
    return (
      <div style={{ borderTop: '1px solid #33354a', paddingTop: '6px', marginTop: '6px' }}>
        <button onClick={() => setOpenSections((o) => ({ ...o, [id]: !isOpen }))}
          style={{ width: '100%', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'none', border: 'none', color: '#8be9fd', fontSize: '0.95rem', fontWeight: 600, padding: '6px 0', cursor: 'pointer', textAlign: 'left' }}>
          <span>{title}{count != null ? <span style={{ color: '#6272a4', fontWeight: 400 }}> · {count}</span> : null}</span>
          <span style={{ fontSize: '0.8rem' }}>{isOpen ? '▼' : '▶'}</span>
        </button>
        {isOpen && <div style={{ paddingBottom: '6px' }}>{children}</div>}
      </div>
    );
  };
  // Timeline grouped by month, newest first, so a year of entries reads as headings.
  const byMonth = (rows) => {
    const groups = [];
    for (const r of rows || []) {
      const m = (r.day || '').slice(0, 7);
      const g = groups.find((x) => x.month === m);
      if (g) g.rows.push(r); else groups.push({ month: m, rows: [r] });
    }
    return groups;
  };
  const monthName = (ym) => {
    const [y, m] = ym.split('-').map(Number);
    return isNaN(m) ? ym : new Date(y, m - 1, 1).toLocaleString(undefined, { month: 'long', year: 'numeric' });
  };
  const kindLabel = { person: 'People', place: 'Places', org: 'Organisations', thing: 'Things' };

  return (
    <div onClick={onClose} style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', zIndex: 10000, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '10px' }}>
      <div onClick={(e) => e.stopPropagation()} style={{ background: '#22232a', color: '#f8f8f2', borderRadius: '10px', padding: '18px', width: 'min(760px, 96vw)', maxHeight: '92vh', overflowY: 'auto', border: '1px solid #44475a', position: 'relative' }}>
        <button className="modal-close" onClick={onClose} aria-label="Close">×</button>
        <h2 style={{ margin: '0 0 4px 0', color: '#50fa7b', fontSize: '1.15rem' }}>What Zynkbot knows about you</h2>
        <p style={muted}>Read from the memory database on this device. Nothing is sent anywhere. Tap any memory to open it; what you change or delete there changes what Zynkbot knows.</p>

        {error && <p style={{ color: '#ff5555' }}>{error}</p>}
        {!report && !error && <p style={muted}>Reading…</p>}

        {report && (
          <>
            <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', margin: '8px 0' }}>
              <button style={btn} onClick={copy}>{copied ? '✓ Copied' : '📋 Copy as text'}</button>
            </div>

            <p style={p}>{t.memories} memories, {t.links} links between them, {t.entities} named things, across {t.sessions} conversations.</p>
            <p style={muted}>From {(t.first_at || '').slice(0, 10)} to {(t.last_at || '').slice(0, 10)}. {t.dated} memories carry the date something happened and {t.tagged} have tags.{t.pending_enrichment > 0 ? ` ${t.pending_enrichment} older memories are still being annotated in the background; reopen this later.` : ''}</p>

            {report.requested?.length > 0 && (
              <Section id="requested" title="You asked me to remember" count={report.requested.length} open>
                <p style={muted}>Stored word for word from "Remember: ..." (typed or spoken), newest first.</p>
                {report.requested.slice(0, requestedShown).map((x) => <p key={x.id} style={p}><span style={{ color: '#9aa5c4' }}>{x.day}</span>{'  '}{link(x.id, x.title)}</p>)}
                {report.requested.length > requestedShown && (
                  <button style={btn} onClick={() => setRequestedShown((k) => k + 20)}>Show more ({report.requested.length - requestedShown} more)</button>
                )}
              </Section>
            )}

            <Section id="timeline" title="Timeline, by when it happened" count={report.timeline?.length || 0} open>
              {report.timeline?.length ? byMonth(report.timeline).map((g) => (
                <div key={g.month}>
                  <p style={{ ...muted, margin: '8px 0 2px 0', fontWeight: 600 }}>{monthName(g.month)}</p>
                  {g.rows.map((x) => <p key={x.id} style={p}><span style={{ color: '#9aa5c4', fontVariantNumeric: 'tabular-nums' }}>{x.day.slice(8)}</span>{'  '}{link(x.id, x.title)}</p>)}
                </div>
              )) : <p style={muted}>No memory has an event date yet. Say when something happened ("yesterday", "last March") and it will appear here.</p>}
            </Section>

            <Section id="categories" title="Categories" count={report.namespaces?.length || 0}>
              <div>{(report.namespaces || []).map((x, i) => chip(`${x.name} · ${x.count}`, i))}</div>
            </Section>

            <Section id="tags" title="Tags" count={report.tags?.length || 0}>
              <div>{report.tags?.length ? report.tags.map((x, i) => chip(`${x.tag} · ${x.count}`, i, onFilterTag ? () => onFilterTag(x.tag) : undefined)) : <span style={muted}>none yet, tags start with memories stored from now on</span>}</div>
              {report.tags?.length ? <p style={{ ...muted, marginTop: '6px' }}>Tap a tag to see those memories in the list.</p> : null}
            </Section>

            <Section id="entities" title="People, places and things" count={t.entities}>
              {['person', 'place', 'org', 'thing'].map((k) => (
                <p key={k} style={p}><strong style={{ color: '#9aa5c4' }}>{kindLabel[k]}:</strong>{' '}
                  {report.entities?.[k]?.length ? report.entities[k].map((x) => `${x.name} (${x.count})`).join(', ') : 'none yet'}</p>
              ))}
            </Section>

            <Section id="beliefs" title="Belief changes" count={report.belief_changes?.length || 0}>
              {report.belief_changes?.length ? report.belief_changes.map((x, i) => (
                <p key={i} style={p}><span style={{ color: '#9aa5c4' }}>{x.day}</span>{'  '}<em>{x.kind}</em>: {link(x.new_id, `"${x.new_title}"`)} vs {link(x.old_id, `"${x.old_title}"`)}{x.notes ? <span style={{ color: '#9aa5c4' }}> — {x.notes}</span> : null}</p>
              )) : <p style={muted}>No contradictions recorded yet.</p>}
            </Section>

            {report.kitchen?.length > 0 && (
              <Section id="kitchen" title="Kitchen" count={report.kitchen.length}>
                {report.kitchen.map((x) => <p key={x.id} style={p}><span style={{ color: '#9aa5c4' }}>{x.day}</span>{'  '}{link(x.id, x.title)}</p>)}
              </Section>
            )}

            {report.hands_free?.length > 0 && (
              <Section id="handsfree" title="Heard hands-free" count={report.hands_free.length}>
                <p style={muted}>Stored from "Hey Zynk" turns. If one is not you (a TV line, someone else in the room), open it and delete it.</p>
                {report.hands_free.map((x) => <p key={x.id} style={p}><span style={{ color: '#9aa5c4' }}>{x.day}</span>{'  '}{link(x.id, x.title)}</p>)}
              </Section>
            )}

            <Section id="tone" title="Tone" count={(report.tone || []).length}>
              <div>{(report.tone || []).map((x, i) => chip(`${x.label} · ${x.count}`, i))}</div>
            </Section>

            <Section id="recent" title="Most recent memories" count={(report.recent || []).length}>
              {(report.recent || []).map((x) => <p key={x.id} style={p}><span style={{ color: '#9aa5c4' }}>{x.day}</span>{'  '}{link(x.id, x.title)} <span style={{ color: '#6272a4' }}>· {x.namespace}</span></p>)}
            </Section>
          </>
        )}
      </div>
    </div>
  );
}
